[tool.poetry]
name = "lab2"
version = "0.1.0"
description = ""
authors = ["miorezu <m.miorezu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
notebook = "^7.4.1"
numpy = "^2.2.5"
pandas = "^2.2.3"
seaborn = "^0.13.2"
matplotlib = "^3.10.1"
plotly = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
